name = "noesis"
license = "MIT"
licenselink = "https://github.com/josephhutch/noesis/blob/main/LICENSE.md"
description = "Noesis is a blog theme with a calm editorial aesthetic, balancing generous whitespace, subtle typography, and understated visual depth."
homepage = "https://github.com/josephhutch/noesis"
tags = ["blog", "personal", "responsive", "minimal", "simple", "clean", "modern", "technical", "syntax highlighting", "google analytics", "disqus", "material design"]
features = ["Responsive", "Hugo image processing", "Chroma syntax highlighting", "KaTeX", "Google analytics", "Disqus"]

[author]
    name = "Joe Hutchinson"
    homepage = "https://www.joehutch.com"
