baseURL = "https://example.com"
locale = "en-US"
title = "Hugo Themes - noesis"
canonifyURLs = true
theme = "noesis"
themesDir = "../../" 

[pagination]
    pagerSize = 3

[params]
    brand = "noesis"
    description = "noesis Hugo theme for blogs"

    [params.profile]
        headshotImage = "img/headshot.jpg"
        headshotAlt = "Generic grey headshot picture"

    [params.author]
        name = "Joe Hutchinson"

[markup]
  [markup.highlight]
    style = "igor"
